import type { ClassSession } from "@/lib/types";

export const SAMPLE_ID = "ses-sample-along";

export function sampleSession(): ClassSession {
  const startedAt = Date.parse("2026-09-06T12:00:00-07:00");
  return {
    id: SAMPLE_ID,
    title: "Money apps · 理财课",
    startedAt,
    endedAt: startedAt + 48 * 60 * 1000,
    updatedAt: Date.now(),
    sourceId: null,
    sourceTitle: null,
    starred: false,
    starredAt: null,
    coaches: [],
    essays: {},
    notes: [
      {
        id: "jot-sample-1",
        en: "I'd rather use an app than a spreadsheet.",
        zh: "我宁愿用 App，也不用表格。",
        src: "hand",
        at: startedAt + 12 * 60 * 1000,
      },
    ],
    transcript: [
      { en: "Today we're talking about money apps.", zh: "今天我们谈理财应用。" },
      { en: "Some people track every coffee they buy.", zh: "有人会记下每一杯咖啡。" },
      { en: "I'd rather use an app than a spreadsheet.", zh: "我宁愿用应用，也不用表格。" },
      { en: "As long as it is simple, I will actually open it.", zh: "只要简单，我才会打开。" },
      { en: "The risk is you start checking it instead of living.", zh: "风险是你开始刷软件，而不是过日子。" },
      { en: "Not only does it show spending, but it also sets a budget.", zh: "它不但能看支出，还能做预算。" },
    ],
    recap: {
      title: "Money apps · 理财课",
      lede: "The class compared *money apps* with spreadsheets. The useful line was *I'd rather use an app than a spreadsheet*, with a condition: *as long as* it stays simple. The tension: tracking helps, but it can replace living.",
      ledeZh: "这堂课比较理财 App 和表格。有用的句子是「我宁愿用 App，也不用表格」，条件是「只要它够简单」。张力在于：记账有用，但也可能取代生活。",
      outline: [
        {
          heading: "Why people open a money app",
          bullets: [
            "Track small spends so the month is visible",
            "A budget only works if you actually open the app",
          ],
        },
        {
          heading: "App versus spreadsheet",
          bullets: [
            "App is faster; spreadsheet is more control",
            "I'd rather X than Y to state a preference",
          ],
        },
        {
          heading: "The catch",
          bullets: [
            "Checking the app can become the habit",
            "Keep it simple or you will quit",
          ],
        },
        {
          heading: "How to join the talk",
          bullets: [
            "Give one reason, then one condition",
            "Ask: does tracking change how you spend?",
          ],
        },
      ],
      sections: [
        {
          heading: "Why people open a money app",
          headingZh: "为什么会打开理财 App",
          body: "People do not open a *money app* for fun. They open it so small spends stop disappearing.\n\n1. Tracking makes the month *visible*.\n2. A *budget* is useless if you never look at it.\n3. The class agreed: *as long as* it is simple, they will use it.\n4. If it takes ten taps, they will quit in a week.",
          bodyZh: "打开理财 App 不是为了好玩，是为了让小额支出不再消失。\n\n1. 记账让一个月变得看得见。\n2. 预算如果你从来不看，就没有用。\n3. 课上达成一致：只要够简单，才会用。\n4. 如果要点十下，一周就会放弃。",
        },
        {
          heading: "App versus spreadsheet",
          headingZh: "应用还是表格",
          body: "The contrast of the hour: an *app* versus a *spreadsheet*.\n\n1. An app is faster to log a coffee.\n2. A spreadsheet gives more *control*.\n3. The line to steal: *I'd rather use an app than a spreadsheet*.\n4. You can flip it: I'd rather keep a spreadsheet than pay for an app.",
          bodyZh: "这小时的对比：应用还是表格。\n\n1. 用 App 记一杯咖啡更快。\n2. 表格更可控。\n3. 可直接用的句子：我宁愿用 App，也不用表格。\n4. 也可以反过来：我宁愿自己做表，也不愿为 App 付钱。",
        },
        {
          heading: "The catch",
          headingZh: "问题在哪",
          body: "*Not only* does the app show spending, *but it also* trains a checking habit.\n\n1. The risk is you start checking it *instead of* living.\n2. Notifications turn money into a feed.\n3. A weekly review is calmer than a daily stare.\n4. Keep one rule: open it on purpose, then close it.",
          bodyZh: "它不但显示支出，还会养成反复查看的习惯。\n\n1. 风险是你开始刷软件，而不是过日子。\n2. 通知把钱变成信息流。\n3. 一周看一次，比天天盯着更冷静。\n4. 一条规则：有目的地打开，然后关掉。",
        },
        {
          heading: "How to join the talk",
          headingZh: "怎么接话",
          body: "To join, do not list features. Give a preference, then a condition.\n\n1. I'd rather X than Y, as long as Z.\n2. Ask one question: does tracking change how you spend?\n3. Give one short example from this week.\n4. If you disagree, say the tradeoff, not just no.",
          bodyZh: "接话不要报功能。先说偏好，再加条件。\n\n1. 我宁愿 X 也不 Y，只要 Z。\n2. 问一句：记账会不会改变你怎么花钱？\n3. 举一个这周的短例子。\n4. 如果反对，说取舍，不要只说不。",
        },
      ],
      takeaways: [
        {
          en: "State a preference with I'd rather X than Y.",
          zh: "用 I'd rather X than Y 说偏好。",
        },
        {
          en: "Add a condition with as long as.",
          zh: "用 as long as 加条件。",
        },
        {
          en: "Name the tradeoff: tracking versus living.",
          zh: "点出取舍：记账还是过日子。",
        },
        {
          en: "Keep the tool simple or you will not open it.",
          zh: "工具要简单，否则你不会打开。",
        },
      ],
      topics: [
        { en: "money apps", zh: "理财应用" },
        { en: "budget", zh: "预算" },
        { en: "spreadsheet vs app", zh: "表格还是应用" },
        { en: "habit and attention", zh: "习惯与注意力" },
      ],
      words: [
        {
          en: "budget",
          zh: "预算",
          use: "A plan for spending.",
          useZh: "花钱的计划。",
          example: "I set a coffee *budget* for the month.",
          exampleZh: "我这个月给咖啡设了预算。",
        },
        {
          en: "track",
          zh: "追踪 / 记账",
          use: "Record what you spend.",
          useZh: "把花出去的记下来。",
          example: "I *track* food, not every snack.",
          exampleZh: "我记餐饮，不记每一口零食。",
        },
        {
          en: "spreadsheet",
          zh: "电子表格",
          use: "Rows and columns for numbers.",
          useZh: "用行列记数字。",
          example: "My *spreadsheet* is slower but clearer.",
          exampleZh: "我的表格更慢，但更清楚。",
        },
        {
          en: "habit",
          zh: "习惯",
          use: "Something you do without thinking.",
          useZh: "不用想就会做的事。",
          example: "Checking the app became a *habit*.",
          exampleZh: "刷这个 App 变成了习惯。",
        },
        {
          en: "tradeoff",
          zh: "取舍",
          use: "You gain one thing and lose another.",
          useZh: "得到一样，失去一样。",
          example: "The *tradeoff* is control versus time.",
          exampleZh: "取舍是控制和时间。",
        },
        {
          en: "visible",
          zh: "看得见的",
          use: "Easy to see.",
          useZh: "容易看见。",
          example: "The app makes spending *visible*.",
          exampleZh: "这个 App 让支出看得见。",
        },
        {
          en: "notification",
          zh: "通知",
          use: "A ping from the phone.",
          useZh: "手机弹的提示。",
          example: "I turned *notifications* off at night.",
          exampleZh: "晚上我把通知关了。",
        },
        {
          en: "quit",
          zh: "放弃",
          use: "Stop using something.",
          useZh: "不再用。",
          example: "If it is heavy, I *quit* in a week.",
          exampleZh: "如果很重，我一周就放弃。",
        },
      ],
      collos: [
        {
          en: "set a budget",
          zh: "做预算",
          use: "verb + noun",
          useZh: "动宾搭配",
          example: "I *set a budget* for eating out.",
          exampleZh: "我给下馆子做了预算。",
        },
        {
          en: "track spending",
          zh: "记支出",
          use: "verb + noun",
          useZh: "动宾搭配",
          example: "She *tracks spending* once a week.",
          exampleZh: "她一周记一次支出。",
        },
        {
          en: "open the app",
          zh: "打开应用",
          use: "verb + noun",
          useZh: "动宾搭配",
          example: "I *open the app* on Sunday night.",
          exampleZh: "我周日晚上打开应用。",
        },
        {
          en: "pay for an app",
          zh: "为应用付费",
          use: "verb + for",
          useZh: "动词 + for",
          example: "I won't *pay for an app* I open twice.",
          exampleZh: "只打开两次的 App 我不会付钱。",
        },
        {
          en: "small spends",
          zh: "小额支出",
          use: "adj + noun",
          useZh: "形容词 + 名词",
          example: "*Small spends* add up.",
          exampleZh: "小额支出会积起来。",
        },
        {
          en: "weekly review",
          zh: "每周回顾",
          use: "adj + noun",
          useZh: "形容词 + 名词",
          example: "A *weekly review* is enough.",
          exampleZh: "一周回顾一次就够了。",
        },
      ],
      patterns: [
        {
          en: "I'd rather X than Y",
          zh: "我宁愿 X 也不 Y",
          use: "preference",
          useZh: "说更想要的选择",
          example: "I'd rather *use an app* than a spreadsheet.",
          exampleZh: "我宁愿用 App，也不用表格。",
        },
        {
          en: "as long as",
          zh: "只要",
          use: "condition",
          useZh: "提出条件",
          example: "*As long as* it is simple, I will open it.",
          exampleZh: "只要简单，我就会打开。",
        },
        {
          en: "instead of",
          zh: "而不是",
          use: "swap",
          useZh: "用 A 替代 B",
          example: "Checking the app *instead of* living.",
          exampleZh: "刷软件，而不是过日子。",
        },
        {
          en: "not only … but also",
          zh: "不但…而且",
          use: "add",
          useZh: "递进",
          example: "*Not only* does it show spending, *but it also* sets a budget.",
          exampleZh: "它不但能看支出，还能做预算。",
        },
        {
          en: "The risk is …",
          zh: "风险是…",
          use: "name a downside",
          useZh: "点出坏处",
          example: "*The risk is* you start checking it all day.",
          exampleZh: "风险是你会整天刷。",
        },
      ],
      grammar: [
        {
          en: "I'd rather + verb",
          zh: "宁愿 + 动词原形",
          use: "I'd rather go / use / keep",
          useZh: "rather 后面用动词原形",
          example: "I'd rather *keep* cash this month.",
          exampleZh: "这个月我宁愿留着现金。",
        },
        {
          en: "as long as + clause",
          zh: "只要 + 从句",
          use: "as long as + subject + verb",
          useZh: "后面接完整句子",
          example: "I'll use it *as long as* it stays free.",
          exampleZh: "只要还免费，我就用。",
        },
        {
          en: "not only … but also (inversion)",
          zh: "不但…而且（倒装）",
          use: "Not only does it…, but it also…",
          useZh: "not only 放句首时要倒装",
          example: "*Not only does* it track coffee, *but it also* nags me.",
          exampleZh: "它不但记咖啡，还会催我。",
        },
        {
          en: "instead of + -ing / noun",
          zh: "instead of + 名词或动名词",
          use: "instead of living / instead of a spreadsheet",
          useZh: "后面接名词或 doing",
          example: "Log it *instead of* guessing.",
          exampleZh: "记下来，而不是猜。",
        },
      ],
      lines: [
        {
          en: "I'd rather use an app than a spreadsheet.",
          zh: "我宁愿用 App，也不用表格。",
          use: "preference",
          useZh: "说选择",
          example: "I'd rather cook than order in.",
          exampleZh: "我宁愿做饭，也不点外卖。",
        },
        {
          en: "As long as it is simple, I will actually open it.",
          zh: "只要简单，我才会打开。",
          use: "condition",
          useZh: "加条件",
          example: "As long as it's Sunday, I review.",
          exampleZh: "只要是周日，我就回顾。",
        },
        {
          en: "The risk is you start checking it instead of living.",
          zh: "风险是你开始刷软件，而不是过日子。",
          use: "tradeoff",
          useZh: "说取舍",
          example: "The risk is I buy tools instead of using them.",
          exampleZh: "风险是我买工具却不用。",
        },
        {
          en: "Not only does it show spending, but it also sets a budget.",
          zh: "它不但能看支出，还能做预算。",
          use: "add a point",
          useZh: "再加一层",
          example: "Not only is it free, but it also works offline.",
          exampleZh: "它不但免费，还能离线用。",
        },
        {
          en: "Keep one rule: open it on purpose, then close it.",
          zh: "一条规则：有目的地打开，然后关掉。",
          use: "give a rule",
          useZh: "给一条规则",
          example: "Open it on Sunday, then close it.",
          exampleZh: "周日打开，然后关掉。",
        },
      ],
      skills: [
        { en: "I'd rather X than Y, as long as Z.", zh: "先说偏好，再加条件。" },
        { en: "Ask: does tracking change how you spend?", zh: "追问：记账有没有改变你花钱的方式？" },
        { en: "Give one example from this week, then the tradeoff.", zh: "举这周一个例子，再说取舍。" },
      ],
      coachPack: [],
      marks: ["money app", "spreadsheet", "as long as", "tradeoff", "budget"],
      draft: false,
      latencyMs: 0,
      at: Date.now(),
    },
  };
}
